// Generated by scripts/prepare-images.mjs — do not edit by hand.
export const BLUR: Record<string, string> = {
  "hero": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAkAA8BgJbACdAEKy/cB3fgAAP3ju/H+LHDc3wIuye5he9SKUtgNGGIr4HZ3dy+quo13eXphT0wpUcBXXf4nyVSOGwJTV+MbQc1IbeP4r9BD9iBYtrcPBgaKugAA",
  "taipei-green": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAkAA8BgJaACdAD0ozxowjoAAP7wq0hJXcnEOdWhTHfTI5+p+28cXiFDow6EFMdeoQbDeEt2uNASbgAAAA==",
  "trade-routes": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAkAA8BgJbACdDiMwVKy4MYu6oAA/tYqcUaVZseu3I57im36RAKGtQGLEr1z5MuN/7jcrbrf5Bd3RPrWOrQzoO6NJHkfVtfXdu8rFpoOoN9xSaoAAA==",
  "contact": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA8BgJYwCdADZI56SgAD9UgPd3GujT1z/eJdSIu9v9ZwdHwEFGxIpD5RozljQL/DHXvr17N2ftuZUdKkzB3IjAAAA",
  "about": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA8BgJZgCdH8AFbbhntJwAP7zmxh0gw0lhdquDjamWG3kfMCIh3iL3Fq/23Eu7FrlDGDRxI0PcvEZBqSppVfKTy/tFk0qN4JFQPJbg1ab4AA=",
  "bridge": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkAA8BgJQBOgCP/hU99v0AA/mzXRSpJf6077M7OD6DFuTOADKQ3eiISGa/yGbuksu8VzH0uVSAA",
  "india-growth": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAgAA8BgJYgCdAD0n17luaAA/vOqjybNlkf3b/dug/vG2Vej5cRVy8Y4xKEBfE31xcaCA+He1injM6WrWZJ3mRE5sAAA",
  "capabilities": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA8BgJZQCdAEK0cR5AKAA/u46Fmcpau6zyy0eX/kfl0vb8L1CHU4RaoC773lnlPq4KkZnDxBG8kxi9QVfXac2hJg278btxsQFRcAAAA==",
  "insights": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkABUB8JbACdAD0NSAzQAD8j6f2y+fGFGWdTTY0PdwsCMyRCMs227gXUCBnNIYLp5J5zJZGYpxoI1qyqUAA",
  "industries": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA8BgJQBOgBuRBmVsYAD4tYqWTuCvOD6lX4U4VpSNFixXO9TOgFLj0RDjKnrB0ecfBPwfE7HaOXEMhT3BxGGdYAAA"
};
