/**
 * Optimises every supplied photograph for the web and writes a manifest of
 * blur placeholders that lib/images.ts consumes.
 * Run with: node scripts/prepare-images.mjs
 */
import sharp from 'sharp';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT = path.resolve('public/brand');

const JOBS = [
  { src: 'Images/hero image.png', name: 'hero', width: 2200 },
  { src: 'Images/2.png', name: 'about', width: 1800 },
  { src: 'Images/3.png', name: 'bridge', width: 1800 },
  { src: 'Images/ChatGPT Image Jul 31, 2026, 04_54_52 PM.png', name: 'india-growth', width: 1800 },
  { src: 'Images/4.png', name: 'capabilities', width: 1800 },
  { src: 'Images/5.png', name: 'industries', width: 1800 },
];

async function main() {
  await mkdir(OUT, { recursive: true });
  const manifest = {};

  for (const job of JOBS) {
    const src = path.resolve(job.src);
    const meta = await sharp(src).metadata();

    await sharp(src)
      .resize({ width: job.width, withoutEnlargement: true })
      .webp({ quality: 80, effort: 5 })
      .toFile(path.join(OUT, `${job.name}.webp`));

    const blur = await sharp(src).resize(16).webp({ quality: 35 }).toBuffer();
    manifest[job.name] = `data:image/webp;base64,${blur.toString('base64')}`;

    console.log(`${job.name}: ${meta.width}x${meta.height} -> ${job.name}.webp`);
  }

  const ts = `// Generated by scripts/prepare-images.mjs — do not edit by hand.
export const BLUR: Record<string, string> = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(path.resolve('lib/blur.ts'), ts, 'utf8');
  console.log('wrote lib/blur.ts');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
